### ISSUE TITLE
code review and refactoring for milestone 1,2,3

### ISSUE THREAD

**Issue by qianxiaofeng** [eosiosg/nodeos-tps#1]

**Comment by qianxiaofeng** [comment]
review checklist
- [ ] code style, 代码风格跟std保持一致, IDE自动排版配置
- [ ] unit test, 拆分复杂逻辑变为可测试逻辑
- [ ] c++及boost版本使用新版本写法, 例如c++使用shared_ptr, boost asio使用io_context
- [ ] OO封装, 设计模式
